# Generated by Django 4.1.2 on 2022-11-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="pet"),
        ),
    ]
