# Generated by Django 4.1.2 on 2022-11-26 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet_app", "0002_alter_pet_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="descripcion",
            field=models.CharField(max_length=200),
        ),
    ]
